# Jekyll configuration
title: Shubhanshu Mishra
description: Researcher in Information Science
url: shubhanshu.com
markdown: GFM

google_analytics: UA-44393164-1


theme_config:
  social_links:
    twitter: TheShubhanshu
    github: napsternxg
    linkedin: shubhanshumishra
  
  scholarly_links:
    google_scholar: 013OA04AAAAJ
    microsoft_academic: "2192659826"
    semantic_scholar: Shubhanshu-Mishra/2777543
    orcid: 0000-0001-9931-1690
    publons: "1275221"
